server:
  port: 8080
spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      routes:
        - id: service-car-sharing
          uri: lb://SERVICE-CAR-SHARING
          predicates:
            - Path=/service-carsharing/**
          filters:
            - RewritePath=/service-carsharing/(?<path>.*),/$\{path}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
